server:
  port: "8080"
  readtimeout: "10s"
  writetimeout: "10s"
  idletimeout: "60s"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "urlshortener"
  sslmode: "disable"
  maxopenconns: 25
  maxidleconns: 5
  connmaxlifetime: "5m"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  poolsize: 10
  minidleconns: 5

app:
  baseurl: "http://localhost:8080"
  cachettl: "24h"
  snowflakenodeid: 1
  ratelimitrequests: 100
  ratelimitwindow: "1m"
